server:
  port: 9100

#服务名称
spring:
  application:
    name: config-service
#git配置
  cloud:
    config:
      server:
        git:
          uri: https://github.com/EssinZhang/Cloud-Config
          #超时时间
          timeout: 5
          #分支
          default-label: master
          skip-ssl-validation: true

#指定注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


