server:
  port: 8781

#指定注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#服务名称
spring:
  application:
    name: order-service

#开启feign对hystrix的支持
feign:
  hystrix:
    enabled: true
  client:
    default-config:
      connectTimeout: 2000
      readTimeout: 2000

