server:
  port: 8781

#指定注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#服务名称
spring:
  application:
    name: order-service
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 2000
  zipkin:
    base-url: http://39.97.232.41:9411/
  #配置采样百分比，开发环境可以设置为1
  sleuth:
    sampler:
      probability: 1

#开启feign对hystrix的支持
feign:
  hystrix:
    enabled: true
  client:
    default-config:
      connectTimeout: 2000
      readTimeout: 2000

##把hystrix超时时间禁用
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: false

#修改超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

#endpoint  断路器Dashboard  * 暴露全部监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"
